services:
  db:
    image: postgis/postgis:16-3.4
    container_name: bucegi_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
  web:
    build: .
    container_name: bucegi_geodjango
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn bucegi_map.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8095:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DJANGO_ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: bucegi_nginx
    restart: unless-stopped
    ports:
      - "8097:80"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl/map.bucegipark.ro.crt:/etc/nginx/ssl/map.bucegipark.ro.crt:ro
      - ./nginx/ssl/map.bucegipark.ro.key:/etc/nginx/ssl/map.bucegipark.ro.key:ro
      - static_volume:/static:ro
    depends_on:
      - web

volumes:
  static_volume:
  db_data: